"""added student_id field to conversations

Revision ID: a9384ea5391d
Revises: 00cf6e3ef2fe
Create Date: 2022-07-05 03:28:05.566168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9384ea5391d'
down_revision = '00cf6e3ef2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('student_id', sa.String(length=200), nullable=True))
    op.execute("UPDATE conversation SET student_id = 'None'")
    op.alter_column('conversation', 'student_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'student_id')
    # ### end Alembic commands ###
