"""Add for_staff column in FAQ table

Revision ID: 6abdff1e514e
Revises: 5c71b3cbebbc
Create Date: 2025-02-28 16:08:54.744786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abdff1e514e'
down_revision = '5c71b3cbebbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_staff', sa.Boolean(), nullable=True))
    
    op.execute("UPDATE faq SET for_staff = FALSE WHERE for_staff IS NULL")
    
    # Alter column to NOT NULL
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('for_staff', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_column('for_staff')

    # ### end Alembic commands ###
