"""added faq table

Revision ID: 98d6b8dd7844
Revises: 
Create Date: 2022-03-25 13:34:53.987065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d6b8dd7844'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('patterns', sa.String(), nullable=False),
    sa.Column('responses', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.add_column('query', sa.Column('faq_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'query', 'faq', ['faq_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.drop_column('query', 'faq_id')
    op.drop_table('faq')
    # ### end Alembic commands ###
