"""add unique constraint for faq table

Revision ID: 9cecfff839a0
Revises: 6abdff1e514e
Create Date: 2025-03-03 18:10:59.238574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cecfff839a0'
down_revision = '6abdff1e514e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_constraint('faq_tag_key', type_='unique')
        batch_op.create_unique_constraint('unique_faq_tag', ['tag', 'for_staff'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_constraint('unique_faq_tag', type_='unique')
        batch_op.create_unique_constraint('faq_tag_key', ['tag'])

    # ### end Alembic commands ###
